name: Homes
version: @version@
main: com.masahirosaito.spigot.homes.Homes
#main: com.github.m4kvn.spigot.Homes
api-version: @api-version@
authors: [m4kvn]
description: This plugin allows each player to set their home point.
website: https://github.com/m4kvn/spigot-home
load: POSTWORLD
commands:
  home:
    description: Homes Command
    usage: /<command>
permissions:
  homes.*:
    description: Grant all permissions of Homes.
    default: op
    children:
      homes.update: true
      homes.reload: true
      homes.general: true
  homes.general:
    description: Grant general permissions of Homes.
    default: false
    children:
      homes.command: true
      homes.command.name: true
      homes.command.player: true
      homes.command.player.name: true
      homes.command.set: true
      homes.command.set.name: true
      homes.command.list: true
      homes.command.list.player: true
      homes.command.delete: true
      homes.command.delete.name: true
      homes.command.help: true
      homes.command.help.command: true
      homes.command.private: true
      homes.command.invite: true
      homes.command.invite.name: true
